sudo: false
language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: acsbidoul
  password:
    secure: ""
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
  on:
    repo: acsone/click-odoo-contrib
    branch: master
    tags: true
